// Re-export all shared types from @bitk/shared
// This file exists for backwards compatibility — imports from '@/types/kanban'
// continue to work while new code can import directly from '@bitk/shared'.
export type {
  ApiResponse,
  BusyAction,
  CategorizedCommands,
  CommandCategory,
  DirectoryListing,
  EngineAvailability,
  EngineDiscoveryResult,
  EngineModel,
  EngineProfile,
  EngineSettings,
  EngineType,
  ExecuteIssueRequest,
  ExecuteIssueResponse,
  FileChange,
  FileContent,
  FileEntry,
  FileListingResult,
  Issue,
  IssueChangedFile,
  IssueChangesResponse,
  IssueFilePatchResponse,
  IssueLogsResponse,
  LogEntryType,
  NormalizedLogEntry,
  Note,
  PermissionMode,
  ProbeResult,
  ProcessInfo,
  Project,
  ProjectProcessesResponse,
  SessionStatus,
  ToolAction,
  ToolDetail,
} from '@bitk/shared'
